###
# URLs
###
[build.processing.html]
  pretty_urls = true

[build]
  publish = "_site"
  command = "npm run build-production"

[[plugins]]
package = "./plugins/keep-data-cache"

[[headers]]
  for = "/api/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Referrer-Policy = "strict-origin-when-cross-origin, no-referrer-when-downgrade"

[context.branch-deploy.environment]
  PUPPETEER_CACHE_DIR = "/opt/build/repo/node_modules/.cache/puppeteer-bin/"

[context.deploy-preview.environment]
  PUPPETEER_CACHE_DIR = "/opt/build/repo/node_modules/.cache/puppeteer-bin/"

[context.production.environment]
  PUPPETEER_CACHE_DIR = "/opt/build/repo/node_modules/.cache/puppeteer-bin/"